// <auto-generated />
using System;
using BacBo.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BacBo.Migrations
{
    [DbContext(typeof(BacBoContext))]
    partial class BacBoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.22");

            modelBuilder.Entity("BacBo.Models.BacBoResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BankerFirstRoll")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BankerScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BankerSecondRoll")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BankerWins")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerFirstRoll")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerSecondRoll")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PlayerWins")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Tie")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BacBoResults");
                });

            modelBuilder.Entity("BacBo.Models.RoulletteResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DrawNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RouletteResults");
                });
#pragma warning restore 612, 618
        }
    }
}
